env: test
spring:
  rabbitmq:
    host: 172.20.10.2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: supconit
    url: jdbc:mysql://172.20.10.2:3306/microservice?characterEncoding=utf-8&useSSL=false