env: dev7
spring:
  rabbitmq:
    host: 192.168.253.4
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: supconit
    url: jdbc:mysql://192.168.253.4:3306/microservice?characterEncoding=utf-8&useSSL=false
